"""Run persistence.

A run is a directory::

    runs/<YYYYMMDD-HHMMSS>_<name>/
      run.json            manifest: prompt digest, provider, model, selection
      prompt.md           frozen copy of the monitor instructions
      results/<id>.json   validated Result per trajectory
      raw/<id>.json       verbatim provider response, attempts, timing
      results.jsonl       every result, regenerated by finalize()

Every write is atomic (temp file then ``os.replace``) and happens the
moment a trajectory completes, so a crash or Ctrl-C loses at most the
in-flight calls. A run is resumed by skipping ids that already have an
``ok`` result.
"""

import json
import os
import pathlib
import tempfile
from typing import Any

from pharos import clock
from pharos import schema

MANIFEST_FILE = "run.json"
PROMPT_FILE = "prompt.md"
RESULTS_DIR = "results"
RAW_DIR = "raw"
RESULTS_JSONL = "results.jsonl"

_TEMP_PREFIX = ".tmp_"

Manifest = dict[str, Any]


def new_run_dir(root: str | pathlib.Path, name: str) -> pathlib.Path:
  """Creates a fresh run directory under ``root``.

  Args:
    root: Directory that holds all runs.
    name: Human-readable run name; the directory is ``<stamp>_<name>``.

  Returns:
    The created directory, with ``results/`` and ``raw/`` inside.

  Raises:
    FileExistsError: If a run with the same stamp and name already exists.
  """
  run_dir = pathlib.Path(root) / f"{clock.stamp()}_{name}"
  (run_dir / RESULTS_DIR).mkdir(parents=True, exist_ok=False)
  (run_dir / RAW_DIR).mkdir(exist_ok=True)
  return run_dir


def atomic_write_json(path: pathlib.Path, obj: Any) -> None:
  """Writes ``obj`` as JSON so readers never observe a partial file.

  Args:
    path: Destination; parent directories are created.
    obj: Any JSON-serialisable value.
  """
  path.parent.mkdir(parents=True, exist_ok=True)
  fd, tmp = tempfile.mkstemp(prefix=_TEMP_PREFIX, dir=str(path.parent))
  try:
    with os.fdopen(fd, "w", encoding="utf-8") as f:
      json.dump(obj, f, ensure_ascii=False, indent=1)
    os.replace(tmp, path)
  except BaseException:
    # Leave no half-written temp file behind, whatever interrupted us.
    pathlib.Path(tmp).unlink(missing_ok=True)
    raise


def write_manifest(run_dir: pathlib.Path, manifest: Manifest) -> None:
  """Writes the run manifest."""
  atomic_write_json(run_dir / MANIFEST_FILE, manifest)


def read_manifest(run_dir: str | pathlib.Path) -> Manifest:
  """Returns the run manifest, or an empty dict if none exists yet."""
  path = pathlib.Path(run_dir) / MANIFEST_FILE
  if not path.exists():
    return {}
  manifest: Manifest = json.loads(path.read_text(encoding="utf-8"))
  return manifest


def write_prompt(run_dir: pathlib.Path, instructions: str) -> None:
  """Freezes the monitor instructions alongside the run."""
  (run_dir / PROMPT_FILE).write_text(instructions, encoding="utf-8")


def read_prompt(run_dir: str | pathlib.Path) -> str:
  """Returns the frozen instructions, or ``""`` if the run has none."""
  path = pathlib.Path(run_dir) / PROMPT_FILE
  return path.read_text(encoding="utf-8") if path.exists() else ""


def write_result(run_dir: pathlib.Path, result: schema.Result) -> pathlib.Path:
  """Persists one trajectory's result.

  Args:
    run_dir: The run directory.
    result: The validated result.

  Returns:
    The file written.
  """
  path = run_dir / RESULTS_DIR / f"{result['traj_id']}.json"
  atomic_write_json(path, result)
  return path


def write_raw(run_dir: pathlib.Path, traj_id: str, raw: Any) -> str:
  """Persists the verbatim provider exchange for one trajectory.

  Args:
    run_dir: The run directory.
    traj_id: The trajectory id.
    raw: Provider response, attempts and timing, JSON-serialisable.

  Returns:
    The path written, relative to ``run_dir``, for the result to cite.
  """
  relative = f"{RAW_DIR}/{traj_id}.json"
  atomic_write_json(run_dir / relative, raw)
  return relative


def load_results(run_dir: str | pathlib.Path) -> dict[str, schema.Result]:
  """Returns every persisted result, keyed by trajectory id."""
  out: dict[str, schema.Result] = {}
  for path in sorted((pathlib.Path(run_dir) / RESULTS_DIR).glob("*.json")):
    result: schema.Result = json.loads(path.read_text(encoding="utf-8"))
    out[result["traj_id"]] = result
  return out


def completed_ids(run_dir: str | pathlib.Path) -> set[str]:
  """Returns ids whose result is usable, i.e. what a resume may skip."""
  return {
      traj_id
      for traj_id, result in load_results(run_dir).items()
      if schema.is_ok_status(str(result.get("execution_status", "")))
  }


def finalize(run_dir: pathlib.Path) -> Manifest:
  """Regenerates ``results.jsonl`` and records totals in the manifest.

  Safe to call more than once; each call reflects the results on disk.

  Args:
    run_dir: The run directory.

  Returns:
    The updated manifest.
  """
  results = load_results(run_dir)
  with open(run_dir / RESULTS_JSONL, "w", encoding="utf-8") as f:
    for traj_id in sorted(results):
      f.write(json.dumps(results[traj_id], ensure_ascii=False) + "\n")

  status_counts: dict[str, int] = {}
  verdict_counts: dict[str, int] = {}
  for result in results.values():
    status = result["execution_status"]
    status_counts[status] = status_counts.get(status, 0) + 1
    verdict = result.get("verdict") or "none"
    verdict_counts[verdict] = verdict_counts.get(verdict, 0) + 1

  manifest = read_manifest(run_dir)
  manifest.update(
      {
          "finished_at": clock.now_iso(),
          "n_results": len(results),
          "status_counts": status_counts,
          "verdict_counts": verdict_counts,
      }
  )
  write_manifest(run_dir, manifest)
  return manifest
